services:
  app:
    image: resv-fe-dev
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    volumes:
      - ./client:/usr/src/app
    container_name: resv-fe-dev

  server:
    image: resv-be-dev
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/usr/src/app
    env_file:
      - ./server/.env.dev
    container_name: resv-be-dev

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: resv-nginx-dev
    depends_on:
      - app

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - mongo_data:/data/db
      - ./server/config/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: resv-mongo-dev
  
volumes:
  mongo_data: